// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXluIfl5KL1j3dCKKmn_V1qXn_aentT14',
    appId: '1:763244782900:web:9d27f8586fb6af69513161',
    messagingSenderId: '763244782900',
    projectId: 'flash-chat-c9d93',
    authDomain: 'flash-chat-c9d93.firebaseapp.com',
    storageBucket: 'flash-chat-c9d93.firebasestorage.app',
    measurementId: 'G-E5SGTF7MCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN3imIs84Pu4Uyd9wiRI9HFU3RZ3FB-wQ',
    appId: '1:763244782900:android:76f7b6081055e29f513161',
    messagingSenderId: '763244782900',
    projectId: 'flash-chat-c9d93',
    storageBucket: 'flash-chat-c9d93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMVUKLSRoWDcFXBtbZ83zw2C8tDO7Mvb8',
    appId: '1:763244782900:ios:61004afa407db88f513161',
    messagingSenderId: '763244782900',
    projectId: 'flash-chat-c9d93',
    storageBucket: 'flash-chat-c9d93.firebasestorage.app',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMVUKLSRoWDcFXBtbZ83zw2C8tDO7Mvb8',
    appId: '1:763244782900:ios:61004afa407db88f513161',
    messagingSenderId: '763244782900',
    projectId: 'flash-chat-c9d93',
    storageBucket: 'flash-chat-c9d93.firebasestorage.app',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXluIfl5KL1j3dCKKmn_V1qXn_aentT14',
    appId: '1:763244782900:web:b68b10c54b0abd40513161',
    messagingSenderId: '763244782900',
    projectId: 'flash-chat-c9d93',
    authDomain: 'flash-chat-c9d93.firebaseapp.com',
    storageBucket: 'flash-chat-c9d93.firebasestorage.app',
    measurementId: 'G-855SN21W1V',
  );
}
